### ISSUE TITLE
Add fonts from Adobe Reader DC 20

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#128]
http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/AcroRdrDC2001220041_en_US.exe

https://web.archive.org/web/20200816153003/http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/AcroRdrDC2001220041_en_US.exe

```
wget http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/AcroRdrDC2001220041_en_US.exe
# extract the AcroRdrDC2001220041_en_US.exe file
cabextract AcroRdrDC2001220041_en_US/Data1.cab
ls Data1/*.otf
```

* AdobePiStd.otf
* CourierStd.otf
* CourierStd_Bold.otf
* CourierStd_BoldOblique.otf
* CourierStd_Oblique.otf
* MinionPro_Bold.otf
* MinionPro_BoldIt.otf
* MinionPro_It.otf
* MinionPro_Regular.otf
* MyriadCAD.otf
* MyriadPro_Bold.otf
* MyriadPro_BoldIt.otf
* MyriadPro_It.otf
* MyriadPro_Regular.otf

**Comment by ronaldtse** [comment]
@alexeymorozov I ran into a problem with create-formula. Seems that it's treating the archive as a Zip file, but it's actually msi. How do we specify that?

```sh
$ bin/fontist create-formula --mirror https://web.archive.org/web/20200816153003/http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/AcroRdrDC2001220041_en_US.exe http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/AcroRdrDC2001220041_en_US.exe

Downloads: 169MB/169MB (100.00%)
Traceback (most recent call last):
	19: from bin/fontist:7:in `<main>'
	18: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	17: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	16: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	14: from /Users/me/src/fontist/fontist/lib/fontist/cli.rb:16:in `create_formula'
	13: from /Users/me/src/fontist/fontist/lib/fontist/import/create_formula.rb:21:in `call'
	12: from /Users/me/src/fontist/fontist/lib/fontist/import/create_formula.rb:32:in `formula'
	11: from /Users/me/src/fontist/fontist/lib/fontist/import/create_formula.rb:62:in `font_files'
	10: from /Users/me/src/fontist/fontist/lib/fontist/import/extractors/zip_extractor.rb:14:in `extract'
	 9: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 8: from /Users/me/src/fontist/fontist/lib/fontist/import/extractors/zip_extractor.rb:15:in `block in extract'
	 7: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/file.rb:121:in `open'
	 6: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/file.rb:121:in `new'
	 5: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/file.rb:91:in `initialize'
	 4: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/file.rb:91:in `open'
	 3: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/file.rb:92:in `block in initialize'
	 2: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/central_directory.rb:136:in `read_from_stream'
	 1: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/central_directory.rb:103:in `read_e_o_c_d'
/Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib/zip/central_directory.rb:143:in `get_e_o_c_d': Zip end of central directory signature not found (Zip::Error)

```

**Comment by alexeymorozov** [comment]
I’ve tried the file yesterday with all our three extractors: msi (ole), cab, and zip. Seems that it doesn’t work with any of them.

Also tried to compare with the ClearType archive. The ‘file’ utility returns the same info for them, but the cab extractor doesn’t work.

**Comment by ronaldtse** [comment]
7-zip extractor seems to work on the command-line. 

Can you try this?
https://github.com/masamitsu-murase/seven_zip_ruby

```sh
$ 7z l AcroRdrDC2001220041_en_US.exe 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 177434160 bytes (170 MiB)

Listing archive: AcroRdrDC2001220041_en_US.exe

--
Path = AcroRdrDC2001220041_en_US.exe
Type = PE
Physical Size = 177434160
CPU = x86
Characteristics = Executable 32-bit NoRelocs
Created = 2020-07-31 06:04:28
Headers Size = 1024
Checksum = 177437550
Name = AdobeSelfExtractor.exe
Image Size = 177463296
Section Alignment = 4096
File Alignment = 512
Code Size = 233984
Initialized Data Size = 177191424
Uninitialized Data Size = 0
Linker Version = 12.0
OS Version = 5.1
Image Version = 0.0
Subsystem Version = 5.1
Subsystem = Windows GUI
DLL Characteristics = NX-Compatible TerminalServerAware
Stack Reserve = 1048576
Stack Commit = 4096
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment = FileVersion: 20.12.20041.1044
FileVersion: 20.12.20041.394260
ProductVersion: 20.12.20041.1044
ProductVersion: 20.12.20041.394260
CompanyName: Adobe Systems Incorporated
FileDescription: Adobe Self Extractor
InternalName: AdobeSelfExtractor.exe
LegalCopyright: Copyright  2020 Adobe Systems Incorporated.  All rights reserved.
OriginalFilename: AdobeSelfExtractor.exe
ProductName: Adobe Self Extractor
----
Path = .rsrc/ARCHIVE_7Z/131
Size = 176947379
Packed Size = 176947379
--
Path = .rsrc/ARCHIVE_7Z/131
Type = 7z
Physical Size = 176947379
Headers Size = 338
Method = LZMA:24 BCJ2
Solid = +
Blocks = 1

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2015-03-17 16:35:55 ....A    175114043    176947041  Data1.cab
2015-03-17 16:42:22 ....A      2792960               AcroRead.msi
2020-07-31 11:40:41 ....A          608               abcpy.ini
2020-07-31 11:40:41 ....A          214               setup.ini
2020-07-31 11:40:41 ....A       468528               setup.exe
2020-07-31 11:40:41 ....A    245903360               AcroRdrDCUpd2001220041.msp
------------------- ----- ------------ ------------  ------------------------
2020-07-31 11:40:41          424279713    176947041  6 files
```

**Comment by ronaldtse** [comment]
Apparently that particular file is a 7-zip file. 

This works, but this gem requires native building.

```rb
require 'seven_zip_ruby'

File.open("AcroRdrDC2001220041_en_US.exe", "rb") do |file|
  SevenZipRuby::Reader.extract_all(file, "path_to_dir")
end
```

```
-rw-r--r--@ 1 me  staff   169M Aug 10 17:14 AcroRdrDC2001220041_en_US.exe
drwxr-xr-x  8 me  staff   256B Sep 13 22:10 path_to_dir/

./path_to_dir:
total 859928
-rw-r--r--  1 me  staff   235M Jul 31 11:40 AcroRdrDCUpd2001220041.msp
-rw-r--r--  1 me  staff   2.7M Mar 17  2015 AcroRead.msi
-rw-r--r--  1 me  staff   167M Mar 17  2015 Data1.cab
-rw-r--r--  1 me  staff   608B Jul 31 11:40 abcpy.ini
-rw-r--r--  1 me  staff   458K Jul 31 11:40 setup.exe
-rw-r--r--  1 me  staff   214B Jul 31 11:40 setup.ini
```

**Comment by ronaldtse** [comment]
Done in https://github.com/fontist/formulas/pull/30
