### ISSUE TITLE
Google Fonts update failing, move workflow to formulas repo

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#253]
Has been failing for a while, sample fail:
https://github.com/fontist/fontist/runs/3157152483?check_suite_focus=true

```
/home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:96:in `formula': no implicit conversion of String into Integer (TypeError)
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:83:in `up_to_date?'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:71:in `font_new?'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:59:in `new?'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:35:in `block (2 levels) in fetch_new_paths'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:50:in `log_font'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:34:in `block in fetch_new_paths'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:33:in `select'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:33:in `fetch_new_paths'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google/new_fonts_fetcher.rb:19:in `call'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google_check.rb:19:in `new_fonts'
	from /home/runner/work/fontist/fontist/lib/fontist/import/google_check.rb:8:in `call'
	from bin/check_google:8:in `<main>'
/home/runner/work/fontist/fontist/tmp/fonts/apache/aclonica, 
```

This workflow should probably be moved to the fontist/formulas repository.

**Comment by alexeymorozov** [comment]
@ronaldtse The [branches](https://github.com/fontist/formulas/branches) repo may need to set `v2` as a default branch in order to make the update work.

**Comment by alexeymorozov** [comment]
It works :) It updated 406 formulas on the v2 branch.

**Comment by ronaldtse** [comment]
Great! Thanks @alexeymorozov for the confirmation!
