### ISSUE TITLE
Metanorma checks are failing on Windows right now

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#281]
The Metanorma checks are failing on Windows right now due to some ADoc file inclusion operation. 

https://github.com/fontist/fontist/runs/4971063993?check_suite_focus=true

```
2022-01-27T18:54:37.1526382Z Done: 18:54:37
2022-01-27T18:54:37.2114332Z   processes section split HTML (FAILED - 1)
2022-01-27T18:54:38.3141559Z   use threads number from METANORMA_PARALLEL
2022-01-27T18:54:38.3170164Z 
2022-01-27T18:54:38.3170612Z Metanorma::Input::Asciidoc
2022-01-27T18:54:38.3483472Z asciidoctor: ERROR: test.adoc: line 6: include file not found: D:/a/_temp/rspec-20220127-5452-nz2cc6/common/common-sections/00-abstract.adoc
2022-01-27T18:54:38.3484221Z Cannot continue compiling Asciidoctor document
2022-01-27T18:54:38.3594926Z   aborts if include error
2022-01-27T18:54:38.4037767Z   extracts Asciidoctor document attributes
2022-01-27T18:54:38.4442945Z   extracts Asciidoctor document attributes with default values
2022-01-27T18:54:38.4842655Z   extracts Asciidoctor document attributes for Metanorma
2022-01-27T18:54:38.5241705Z   extracts Asciidoctor document attributes for Metanorma
2022-01-27T18:54:38.5242369Z 
2022-01-27T18:54:38.5242774Z Metanorma::Config
2022-01-27T18:54:38.5243328Z   .configure
2022-01-27T18:54:38.5642114Z     allows us to set our configuration
2022-01-27T18:54:38.5642958Z 
2022-01-27T18:54:38.5643559Z Metanorma::Registry
2022-01-27T18:54:38.6049604Z   has a registry
2022-01-27T18:54:38.6475295Z   deals with multiple aliases
2022-01-27T18:54:38.6971056Z   warns when registered class is not a Metanorma processor
2022-01-27T18:54:38.7699137Z   detects root tag of iso
2022-01-27T18:54:38.9458152Z 
2022-01-27T18:54:38.9458960Z Failures:
2022-01-27T18:54:38.9459205Z 
2022-01-27T18:54:38.9459618Z   1) Metanorma::Compile processes section split HTML
2022-01-27T18:54:38.9461253Z      Failure/Error: expect(File.exist?("#{f}/index.html")).to be true
2022-01-27T18:54:38.9461550Z 
2022-01-27T18:54:38.9461841Z        expected true
2022-01-27T18:54:38.9462146Z             got false
2022-01-27T18:54:38.9462545Z      # ./spec/compile_spec.rb:531:in `block (2 levels) in <top (required)>'
2022-01-27T18:54:38.9462999Z      # ./spec/compile_spec.rb:18:in `block (2 levels) in <top (required)>'
2022-01-27T18:54:38.9463580Z      # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:47:in `block (2 levels) in <module:RSpecCommand>'
2022-01-27T18:54:38.9464255Z      # ./vendor/bundle/ruby/3.0.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:45:in `block in <module:RSpecCommand>'
2022-01-27T18:54:38.9464795Z      # ./spec/spec_helper.rb:30:in `block (4 levels) in <top (required)>'
2022-01-27T18:54:38.9465194Z      # ./spec/spec_helper.rb:30:in `chdir'
2022-01-27T18:54:38.9465617Z      # ./spec/spec_helper.rb:30:in `block (3 levels) in <top (required)>'
2022-01-27T18:54:38.9466084Z      # ./spec/spec_helper.rb:24:in `block (2 levels) in <top (required)>'
2022-01-27T18:54:38.9466466Z 
2022-01-27T18:54:38.9466835Z Finished in 2 minutes 53.6 seconds (files took 6.48 seconds to load)
2022-01-27T18:54:38.9467201Z 57 examples, 1 failure
2022-01-27T18:54:38.9468094Z 
2022-01-27T18:54:38.9468399Z Failed examples:
2022-01-27T18:54:38.9468555Z 
2022-01-27T18:54:38.9468893Z rspec ./spec/compile_spec.rb:519 # Metanorma::Compile processes section split HTML
2022-01-27T18:54:38.9469154Z 
```

_Originally posted by @ronaldtse in https://github.com/fontist/fontist/issues/280#issuecomment-1023762810_

**Comment by opoudjis** [comment]
This is likely the same issue as https://github.com/metanorma/metanorma/issues/233
