### ISSUE TITLE
MSPACK_ERR_OPEN error thrown on metanorma setup

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#29]
In the scope of https://github.com/metanorma/packed-mn/issues/30 I noted that an exception is thrown on `metanorma setup`

```
Metanorma has detected that you do not have the necessary fonts installed
for PDF generation. The generated PDF will use generic fonts that may not
resemble the desired styling. Metanorma can download these files for you
if you accept the font licensing conditions for the font CALIBRI.TTF.

If you want Metanorma to download these fonts for you and indicate your
acceptance of the font licenses, type "Yes" / "No": Yes

Downloads: 60MB/60MB (100.00%)/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/libmspack-0.1.0/lib/libmspack/mscab.rb:695:in `extract': 2 (LibMsPack::Exceptions::LibMsPackError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:51:in `extract_ppviewer_cab_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:56:in `cabbed_fonts'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:39:in `block in extract_ppviewer_fonts'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:38:in `tap'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:38:in `extract_ppviewer_fonts'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:21:in `fetch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/ms_vista_font.rb:17:in `fetch_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/installer.rb:34:in `download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/installer.rb:10:in `download'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-0.2.0/lib/fontist/installer.rb:16:in `download'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:63:in `ask_user_and_download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:45:in `rescue in download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:43:in `download_font'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:23:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/setup.rb:16:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/command.rb:80:in `block in setup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/command.rb:79:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/command.rb:79:in `setup'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli.rb:74:in `start'
	from /__enclose_io_memfs__/local/metanorma:104:in `<main>'
```

After debugging it looks like `assets/ppviewer.cab` doesn't exist, AFAIK it should be packed into gem, is that true?

**Comment by ronaldtse** [comment]
> After debugging it looks like assets/ppviewer.cab doesn't exist, AFAIK it should be packed into gem, is that true?

No, it is a temporary file that is downloaded to extract.

**Comment by ronaldtse** [comment]
@w00lf is this related to packed-mn structure?

**Comment by CAMOBAP** [comment]
@ronaldtse I don't think so because I was able to reproduce this with metanorma-cli gem

**Comment by ronaldtse** [comment]
Ping @abunashir -- I think this happens because Fontist downloads the file to the gem location. In packed-mn and macOS system you cannot modify the filesystem.

Instead, the file should be downloaded to either a TMPDIR or local cache. There must be best practices out there.

**Comment by abunashir** [comment]
Yap, it's mostly related to the permission issue, there are still quite some changes going on, but I will put this in the list and let you guys know as soon as there are some update.

**Comment by abunashir** [comment]
This issue should be resolved with the recent release, @CAMOBAP: Could you please confirm?

**Comment by CAMOBAP** [comment]
@abunashir yep, I can confirm, looks like it was fixed a while ago because I didn't saw this issue last 1-2 weeks already
