### ISSUE TITLE
Support for ArchLinux (from ITU)

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#302]
As described here:
* https://github.com/metanorma/metanorma-itu/issues/327
* https://github.com/metanorma/mn-samples-itu/issues/149

This is a trace from ArchLinux, perhaps Fontist is not compatible with ArchLinux?

```
not a TTC file
Warning: File at /usr/share/fonts/noto/NotoSansCJK-Regular.ttc not recognized as a font file.
not a TTC file
Warning: File at /usr/share/fonts/noto/NotoSerifCJK-Regular.ttc not recognized as a font file.
/usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `block in changed?': undefined method `[]' for #<IO:<STDOUT>> (NoMethodError)
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `changed?'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:120:in `block in do_build_index'
	from <internal:kernel>:90:in `tap'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:119:in `do_build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:108:in `block in build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/utils/locking.rb:11:in `lock'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:107:in `build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:94:in `index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:77:in `find'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:71:in `find_by_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:63:in `find_styles'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:52:in `find_styles'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:74:in `find_font_with_name'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/install.rb:16:in `file_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `flat_map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `style_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `font_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:26:in `call'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:21:in `from_hash'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:47:in `fontist_install'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:28:in `install_fonts_safe'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:95:in `install_fonts'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile_options.rb:57:in `font_install'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile.rb:36:in `compile'
```

**Comment by ronaldtse** [comment]
@maxirmx do you have some time to debug this? Thanks!

**Comment by ronaldtse** [comment]
The Fontist project has not previously considered ArchLinux as a supported platform, we only supported Debian and Ubuntu. Perhaps it is time to add ArchLinux to the mix.

**Comment by ronaldtse** [comment]
Thanks @maxirmx for handling this.

**Comment by maxirmx** [comment]
Fontist tests pass on Arch Linux as is
https://github.com/fontist/fontist/actions/runs/3044445705/jobs/4904842458

I will test with the font that caused the issue -- NotoSansCJK-Regular.ttc

**Comment by ronaldtse** [comment]
Ping @maxirmx on progress, thanks; ITU is waiting for this: https://github.com/metanorma/mn-samples-itu/issues/149#issuecomment-1250247294

**Comment by maxirmx** [comment]
What I did so far
- built/tested fontist on ArchLinux  -- all tests passed
- tested fontist with noto fonts -- worked
- tested metanorma --type itu -x html --agree-to-terms sources/G.191.adoc on ArchLInux -- worked
- tested metanorma --type itu -x html  sources/G.191.adoc (terms not accepted) --  gave reasonable error message

**Comment by maxirmx** [comment]
As far as I ubderstood @bquast has confirmed that --agree-to-terms solved his issue
I believe that the error he got was not related to ArchLinux specifically. There shall be some negative scenario (double/triple failure) that breaks fontist but I am not able to reproduce or  imagine it yet

**Comment by bquast** [comment]
Hi colleagues. Thanks, @maxirmx for tagging me, I hadn't seen this thread yet.

yes `--agree-to-terms` solved the issue. Although there was still quite some output. I have all the fontist packages installed. Let me know if I can can help with debugging.

cheers,
Bastiaan

**Comment by ronaldtse** [comment]
Done and closing.
