### ISSUE TITLE
(URGENT) `cache clear` command fails

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#323]
```sh
fontist cache clear
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/pathname.rb:494:in `unlink': Directory not empty @ dir_s_rmdir - /Users/me/.fontist/downloads/d20210414-20987-17nlkpv (Errno::ENOTEMPTY)
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/pathname.rb:494:in `delete'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/pathname.rb:494:in `each'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/pathname.rb:494:in `each_child'
	from /Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fontist-1.15.0/lib/fontist/cache_cli.rb:9:in `clear'
```

**Comment by ronaldtse** [comment]
@CAMOBAP just want to be sure that we do the following as part of this command:
```sh
rm -f ~/.fontist/system_index.preferred_family.*
rm -rf ~/.fontist/downloads/
```

**Comment by ronaldtse** [comment]
Confirm fixed in #324.

**Comment by ronaldtse** [comment]
@CAMOBAP can you help make a new release for this fix? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse on the way https://github.com/fontist/fontist/actions/runs/4353963915
