### ISSUE TITLE
Fontist update and font installation fails

### ISSUE THREAD

**Issue by Intelligent2013** [fontist/fontist#372]
I'm trying to install the font 'Noto Color Emoji' (for https://github.com/metanorma/metanorma-ogc/issues/655):
`fontist install "Noto Color Emoji"` causes the error:
```
Font "Noto Color Emoji" not found locally.
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/helpers.rb:4:in `parse_to_object': uninitialized constant Fontist::Helpers::OpenStruct (NameError)

      JSON.parse(data.to_json, object_class: OpenStruct)
                                             ^^^^^^^^^^
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula.rb:169:in `resources'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula_picker.rb:181:in `resources_cached?'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula_picker.rb:143:in `block in filter_by_size_limit'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula_picker.rb:142:in `select'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula_picker.rb:142:in `filter_by_size_limit'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula_picker.rb:135:in `ensure_size_limit'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula_picker.rb:32:in `filter'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula_picker.rb:18:in `call'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/font.rb:173:in `sufficient_formulas'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/font.rb:204:in `download_font'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/font.rb:57:in `install'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/font.rb:34:in `install'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/cli.rb:90:in `install'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/exe/fontist:7:in `block in <top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/exe/fontist:28:in `<top (required)>'
        from C:/tools/ruby31/bin/fontist:25:in `load'
        from C:/tools/ruby31/bin/fontist:25:in `<main>'
```

`fontist update` also:
```
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/helpers.rb:4:in `parse_to_object': uninitialized constant Fontist::Helpers::OpenStruct (NameError)

      JSON.parse(data.to_json, object_class: OpenStruct)
                                             ^^^^^^^^^^
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula.rb:189:in `fonts'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/indexes/default_family_font_index.rb:11:in `add_formula'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/indexes/base_index.rb:47:in `block in build'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/indexes/base_index.rb:46:in `each'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/indexes/base_index.rb:46:in `build'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/indexes/base_index.rb:31:in `rebuild'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/index.rb:7:in `rebuild'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/update.rb:55:in `rebuild_index'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/update.rb:15:in `ensure in call'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/update.rb:15:in `call'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/update.rb:4:in `call'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/formula.rb:14:in `update_formulas_repo'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/cli.rb:132:in `update'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/exe/fontist:7:in `block in <top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/exe/fontist:28:in `<top (required)>'
        from C:/tools/ruby31/bin/fontist:25:in `load'
        from C:/tools/ruby31/bin/fontist:25:in `<main>'
```

**Comment by jerstlouis** [comment]
I get a different error trying `fontist install "Noto Emoji"`:

```
/usr/local/bundle/gems/fontist-1.20.0/lib/fontist/font.rb:220:in `request_formula_installation': undefined method `each' for nil:NilClass (NoMethodError)
      paths.each do |path|
           ^^^^^
```

but I realize that you're using Ruby 3.1 but I'm still on 3.0.

Same error on the OGC GitLab pipeline, but I'm not sure what Ruby version that uses (in the metanorma/metanorma docker container).

**Comment by alexeymorozov** [comment]
Yes, I confirm the bug, most of the fonts from Google Fonts couldn't be installed right now. I'll make a quick fix for specific fonts, could you provide a list of fonts do you use?

More information: the Google Fonts [changed](https://github.com/google/fonts/issues/7481#issuecomment-2025656377) the API `fontist` used. We're working on API upgrade [here](https://github.com/fontist/fontist/issues/370).
