### ISSUE TITLE
"cannot load such file -- ffi_c"

### ISSUE THREAD

**Issue by opoudjis** [fontist/fontist#391]
I am quite suddenly getting:

````
bundler: failed to load command: metanorma (/Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/bin/metanorma)
/Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/3.4.0+0/bundled_gems.rb:76:in 'Kernel.require': cannot load such file -- ffi_c (LoadError)
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/3.4.0+0/bundled_gems.rb:76:in 'block (2 levels) in Kernel#replace_require'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/gems/ffi-1.17.1-arm64-darwin/lib/ffi.rb:5:in '<top (required)>'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/3.4.0+0/bundled_gems.rb:76:in 'Kernel.require'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/3.4.0+0/bundled_gems.rb:76:in 'block (2 levels) in Kernel#replace_require'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/gems/sys-uname-1.3.1/lib/sys/unix/uname.rb:3:in '<top (required)>'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/gems/sys-uname-1.3.1/lib/sys/uname.rb:18:in 'Kernel#require_relative'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/gems/sys-uname-1.3.1/lib/sys/uname.rb:18:in '<top (required)>'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/3.4.0+0/bundled_gems.rb:76:in 'Kernel.require'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/3.4.0+0/bundled_gems.rb:76:in 'block (2 levels) in Kernel#replace_require'
	from /Users/nickn/.rbenv/versions/3.4.0-preview2/lib/ruby/gems/3.4.0+0/gems/fontist-1.21.2/lib/fontist/utils/system.rb:1:in '<top (required)>'
````

when I try to run bundle exec metanorma compile on mn-samples-plateau/source/002-v5

I do not know what has changed, and nothing in

https://stackoverflow.com/questions/29092233/how-to-resolve-loaderror-cannot-load-such-file-ffi-c

is working.

**Comment by opoudjis** [comment]
I'm trying to see if Ruby 3.4.1 will address this.

**Comment by opoudjis** [comment]
Now trying to update Command Line Tools for Xcode-16.2, given that I am failing to install seven-zip, and we have had this issue before in https://github.com/metanorma/metanorma/issues/209

The stack is not supposed to be falling over like this.

**Comment by opoudjis** [comment]
I can't install Ruby 3.4.1, after months on the 3.4.0 preview, and I'm reverting back to Ruby 3.3.6. I guess I will wait for a few iterations before going back to Ruby 3.4.1.

**Comment by opoudjis** [comment]
Issue does appear to be specific to Ruby 3.4.x, both the newly released 3.4.1, and the 3.4.0 preview 2 which I had been running for the last few months. 3.3.6 is running fine.
