### ISSUE TITLE
macOS Catalina: unable to detect installed Calibri and hang

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#86]
On a vanilla Catalina with MS Office installed (i.e. Calibri is already available), `brew install metanorma/metanorma/metanorma` was run, which in turn runs `metanorma setup`, which runs Fontist.

Fontist was unable to install Calibri and the process hung as shown below.

The user maybe using system Ruby (`/usr/bin/ruby` and `/usr/bin/gem`) with Homebrew. Could be to do with permissions?

In addition, the correct behavior on a Mac is probably to copy out fonts if they already exist to prevent long/unnecessary download times?

```
$ metanorma setup
nil versions are discouraged and will be deprecated in Rubygems 4
^CTraceback (most recent call last):
	16: from /usr/local/Cellar/metanorma/1.3.1/libexec/bin/metanorma:23:in `<main>'
	15: from /usr/local/Cellar/metanorma/1.3.1/libexec/bin/metanorma:23:in `load'
	14: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/exe/metanorma:20:in `<top (required)>'
	13: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli.rb:61:in `start'
	12: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	10: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 8: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/command.rb:81:in `setup'
	 7: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/command.rb:81:in `each'
	 6: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/command.rb:83:in `block in setup'
	 5: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:16:in `run'
	 4: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:23:in `run'
	 3: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:44:in `download_font'
	 2: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/fontist-1.0.0/lib/fontist/font.rb:15:in `find'
	 1: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/fontist-1.0.0/lib/fontist/font.rb:23:in `find'
/usr/local/Cellar/metanorma/1.3.1/libexec/gems/fontist-1.0.0/lib/fontist/font.rb:63:in `downloadable_font': Fonts are missing, please run Fontist::Font.install('Cambria', confirmation: 'yes') to download the font (Fontist::Errors::MissingFontError)
	22: from /usr/local/Cellar/metanorma/1.3.1/libexec/bin/metanorma:23:in `<main>'
	21: from /usr/local/Cellar/metanorma/1.3.1/libexec/bin/metanorma:23:in `load'
	20: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/exe/metanorma:20:in `<top (required)>'
	19: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli.rb:61:in `start'
	18: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	17: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/command.rb:81:in `setup'
	13: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/command.rb:81:in `each'
	12: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/command.rb:83:in `block in setup'
	11: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:16:in `run'
	10: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:23:in `run'
	 9: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:42:in `download_font'
	 8: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:46:in `rescue in download_font'
	 7: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/setup.rb:62:in `ask_user_and_download_font'
	 6: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/metanorma-cli-1.3.1/lib/metanorma/cli/ui.rb:7:in `ask'
	 5: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/shell.rb:60:in `ask'
	 4: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/shell/basic.rb:85:in `ask'
	 3: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/shell/basic.rb:439:in `ask_simply'
	 2: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/line_editor.rb:7:in `readline'
	 1: from /usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/line_editor/readline.rb:20:in `readline'
/usr/local/Cellar/metanorma/1.3.1/libexec/gems/thor-0.20.3/lib/thor/line_editor/readline.rb:20:in `readline': Interrupt
```

**Comment by abunashir** [comment]
About copying over the existing font is a good idea, I will add that on one straight away.

But for the hang issue, I think it's more related to the download link, by randomization the `ClearTypeFont` might try to download the file from web archive link which is super slow (normally it takes couple of minutes to download). Could you please try couple of times and see if there are any speed improvements?

**Comment by ronaldtse** [comment]
@abunashir Is this a problem with download? In this case can we show some download progress so the user doesn't feel the "hang"?

This issue was reported by @TRThurman . There's no need to re-try for his case since his computer already had Calibri and mn2pdf is able to detect that automatically.

In any case, it calls that Fontist should be tested using macOS system ruby?

**Comment by abunashir** [comment]
@ronaldtse: Turns out we already had the font check option before we run the installer but windows related paths for mac was not included in our lookup list. So I've updated these in the attached PR.

I've also enabled the progress bar for this formula, so during downloads, it will show a percentile for this formula
