### ISSUE TITLE
Wrong detection of HanSans not installed on macOS

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#95]
From @opoudjis :
> In my mac, Fontist is (inaccurately) concluding that HanSans is not installed. Therefore, it attempts to download the font.

From: https://github.com/metanorma/metanorma-cli/issues/164

**Comment by abunashir** [comment]
There could be two reasons why this is happening, first of all, this font is not in the standard font directory or the one we've listed here: https://github.com/fontist/fontist/blob/master/lib/fontist/system.yml#L10, second of all the font name doesn't match with the font names listed in the formula or the name in the user's system. But, I think it's the first one.

I don't have it installed, so I can't debug but could you please add the exact font name and paths to the fonts it is in your system, so I can update the lookup directory?

cc: @opoudjis, @ronaldtse

**Comment by ronaldtse** [comment]
@abunashir it is on @opoudjis 's computer so let's see what path his font is located in. 

On my Mac I have these under `/Library/Fonts/Microsoft/`:
```
-rw-rw-r--@ 1 root  wheel   9.3M Mar 10  2011 SimHei.ttf
-rw-rw-r--@ 1 root  wheel    15M Mar 10  2011 SimSun-ExtB.ttf
-rw-rw-r--@ 1 root  wheel    15M Mar 10  2011 SimSun.ttf
```

<img width="1093" alt="Screen Shot 2020-07-26 at 11 25 16 PM" src="https://user-images.githubusercontent.com/11865/88482959-44d45980-cf97-11ea-90c7-80f6432c5ff0.png">
<img width="1095" alt="Screen Shot 2020-07-26 at 11 25 32 PM" src="https://user-images.githubusercontent.com/11865/88482965-4dc52b00-cf97-11ea-9a5d-d6e5268c18a0.png">
<img width="1090" alt="Screen Shot 2020-07-26 at 11 25 45 PM" src="https://user-images.githubusercontent.com/11865/88482971-54ec3900-cf97-11ea-8277-10efc53a5b7f.png">
<img width="1092" alt="Screen Shot 2020-07-26 at 11 25 53 PM" src="https://user-images.githubusercontent.com/11865/88482973-5a498380-cf97-11ea-8289-311dfb2e2427.png">

**Comment by ronaldtse** [comment]
@abunashir I realized what path is missing -- the user's font path:
- `/Users/{username}/Library/Fonts/*`

**Comment by ronaldtse** [comment]
The `SimSun18030.ttc` (from #69) file is a custom install and usually installed manually in the user's font path:

```
-rw-r--r--@ 1 me  staff    12M Jul 24  2002 SimSun18030.ttc
```
<img width="1365" alt="Screen Shot 2020-07-26 at 11 53 55 PM" src="https://user-images.githubusercontent.com/11865/88483594-6e8f7f80-cf9b-11ea-8fb0-ba9145991802.png">

**Comment by alexeymorozov** [comment]
1. Also the issue could arrive from the fact that during tests `metanorma-cli` stubs the fonts directory with the tmp one. There is no HanSans font by default, so it downloads it.

```ruby
def stub_system_home_directory
  allow(Dir).to receive(:home).
    and_return(Metanorma::Cli.root_path.join("tmp"))
end
```

2. @opoudjis Have you experienced the issue somewhere except tests? May be during local build or something else?

**Comment by ronaldtse** [comment]
@alexeymorozov has fixed the issue in #155 , he will ping @opoudjis .

@alexeymorozov can we make a new gem release? Thanks.

**Comment by ronaldtse** [comment]
Please close when this issue is confirmed fixed, thanks.

**Comment by opoudjis** [comment]
I occasionally randomly get missing font notifications locally, most recently in ITU, which went away after a day. I don't think this has come up recently, but @alexeymorozov could you tell me how to confirm?

**Comment by alexeymorozov** [comment]
Nick, thank you for additional information :)

As was described above, the issue in tests arose from a fact that tests use an empty directory for fonts storage. As I checked it was fixed by stubbing Fontist in metanorma-cli tests (https://github.com/metanorma/metanorma-cli/pull/165).

I think this issue could be closed without new changes (as stubbing is already done).

Though I would do a new release, as @ronaldtse proposed. Some new issues could arise: will support and fix as it happens.

**Comment by opoudjis** [comment]
Btw, I got a font gone missing just today:

SEVERE: Failed to read font file file:/Users/nickn/.metanorma/fonts/times.ttf
java.io.FileNotFoundException: /Users/nickn/.metanorma/fonts/times.ttf (No such file or directory)

~/Documents/Arbeit/upwork/ribose/latexmath[master] $ ls ~/.metanorma/fonts
STIX2Math.otf			SourceSansPro-Bold.ttf		SourceSerifPro-BoldIt.ttf
SourceCodePro-Bold.ttf		SourceSansPro-BoldIt.ttf	SourceSerifPro-It.ttf
SourceCodePro-BoldIt.ttf	SourceSansPro-It.ttf		SourceSerifPro-Regular.ttf
SourceCodePro-It.ttf		SourceSansPro-Light.ttf		pdf_fonts_config.xml.out
SourceCodePro-Regular.ttf	SourceSansPro-LightIt.ttf	source-fonts.zip
SourceHanSans-Bold.ttc		SourceSansPro-Regular.ttf
SourceHanSans-Normal.ttc	SourceSerifPro-Bold.ttf

I've just rerun it, and it did not happen again. I don't understand why...

**Comment by alexeymorozov** [comment]
I'll try to reproduce it. A command, which leads to such an error, will help.

**Comment by opoudjis** [comment]
This happens on attempts to compile an PDF file during rspec. It disappears on rerun. So, in metanorma-bipm

````
java -Xss5m -Xmx1024m -jar /Users/nickn/.rvm/gems/ruby-2.6.6/gems/mn2pdf-1.22.1/lib/../bin/mn2pdf.jar --xml-file "test.presentation.xml" --xsl-file "/Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-bipm/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "test.pdf" 

2020-11-01 22:13:16.578 java[41239:1545432] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 19. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2020-11-01 22:13:16.579 java[41239:1545432] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 19. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
Νοε 01, 2020 10:13:30 ΜΜ org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Νοε 01, 2020 10:13:30 ΜΜ org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
Νοε 01, 2020 10:13:31 ΜΜ org.apache.fop.fonts.LazyFont load
SEVERE: Failed to read font file file:/Users/nickn/.metanorma/fonts/times.ttf
java.io.FileNotFoundException: /Users/nickn/.metanorma/fonts/times.ttf (No such file or directory)
````

However, although that font does not exist at that location, the error is not repeated. The error is triggered by PDF XSLT, so you would need to get further information on its context from @Intelligent2013

**Comment by ronaldtse** [comment]
FYI `java.io.FileNotFoundException: /Users/nickn/.metanorma/fonts/times.ttf (No such file or directory)` is a Java error, it is not a Fontist issue. Fontist is only meant to install the fonts for you in the proper location.

I believe what is needed here is to synchronize mn2pdf to utilize the Fontist paths. @Intelligent2013 could you have a look here? Thanks!

**Comment by Intelligent2013** [comment]
mn2pdf replaces 'not found font' to Source[Sans|Serif|Code]Pro font always.
I've installed Ubuntu and tried these experiments:
#### 1. Run mn2pdf without internet connection. mn2pdf can't find `times.ttf` and tries to replace by `SourceSansPro-Regular.ttf`, but can't download it and exit with `java.io.FileNotFoundException`:
```
java -Xss5m -Xmx1024m -jar mn2pdf-1.22.jar  --xml-file "test.presentation.xml" --xsl-file "bipm.brochure.presentation.xsl" --pdf-file "test.pdf"
mn2pdf 


Preparing...
Input: Fonts path (~/.metanorma/fonts)
Input: XML (test.presentation.xml)
Input: XSL (bipm.brochure.presentation.xsl)
Output: PDF (test.pdf)

Downloading https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip...
Can't downloaded a file: github.com
Can't unzip a file: /home/intluser/.metanorma/fonts/source-fonts.zip (No such file or directory)
Can't find a font file: /home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf
Can't find a font file: /home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf
...
Can't find a font file: /home/intluser/.metanorma/fonts/SourceHanSans-Normal.ttc
Can't find a font file: /home/intluser/.metanorma/fonts/SourceHanSans-Bold.ttc
Can't find a font file: /home/intluser/.metanorma/fonts/STIX2Math.otf
Downloading https://github.com/stipub/stixfonts/raw/master/OTF/STIX2Math.otf...
Can't downloaded a file: github.com
WARNING: Font file '/home/intluser/.metanorma/fonts/arial.ttf' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/arialbd.ttf' (font style 'normal', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/arialbi.ttf' (font style 'italic', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/ariali.ttf' (font style 'italic', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/times.ttf' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesbd.ttf' (font style 'normal', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesbi.ttf' (font style 'italic', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesi.ttf' (font style 'italic', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/SourceHanSans-Normal.ttc' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
....
WARNING: Font file '/home/intluser/.metanorma/fonts/STIX2Math.otf' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
...
WARNING: Font file '/home/intluser/.metanorma/fonts/WorkSans-Thin.ttf' (font style 'normal', font weight '100') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
....
Transforming...
Nov 05, 2020 1:20:38 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Nov 05, 2020 1:20:38 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
Nov 05, 2020 1:20:40 PM org.apache.fop.fonts.LazyFont load
SEVERE: Failed to read font file file:/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf
java.io.FileNotFoundException: /home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
```

#### 2. First run mn2pdf with internet connection. mn2pdf can't find `times.ttf` and replace it by `SourceSansPro-Regular.ttf` successfully (SourceXPro fonts downloaded before successfully) and process PDF successfully:
```
 java -Xss5m -Xmx1024m -jar mn2pdf-1.22.jar  --xml-file "test.presentation.xml" --xsl-file "bipm.brochure.presentation.xsl" --pdf-file "test.pdf"
mn2pdf 


Preparing...
Input: Fonts path (~/.metanorma/fonts)
Input: XML (test.presentation.xml)
Input: XSL (bipm.brochure.presentation.xsl)
Output: PDF (test.pdf)

Downloading https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip...
Extracting font file /home/intluser/.metanorma/fonts/SourceSansPro-It.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceCodePro-Regular.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceCodePro-It.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSerifPro-Bold.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSansPro-Light.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSerifPro-BoldIt.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSerifPro-Regular.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceCodePro-BoldIt.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSansPro-BoldIt.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSansPro-LightIt.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceHanSans-Normal.ttc...
Extracting font file /home/intluser/.metanorma/fonts/SourceCodePro-Bold.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceHanSans-Bold.ttc...
Extracting font file /home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf...
Extracting font file /home/intluser/.metanorma/fonts/SourceSerifPro-It.ttf...
Can't find a font file: /home/intluser/.metanorma/fonts/STIX2Math.otf
Downloading https://github.com/stipub/stixfonts/raw/master/OTF/STIX2Math.otf...
WARNING: Font file '/home/intluser/.metanorma/fonts/arial.ttf' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/arialbd.ttf' (font style 'normal', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/arialbi.ttf' (font style 'italic', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/ariali.ttf' (font style 'italic', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/times.ttf' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesbd.ttf' (font style 'normal', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesbi.ttf' (font style 'italic', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesi.ttf' (font style 'italic', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/WorkSans-Thin.ttf' (font style 'normal', font weight '100') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
....
Transforming...
Nov 05, 2020 11:07:45 AM org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Nov 05, 2020 11:07:45 AM org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
Nov 05, 2020 11:07:50 AM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #1.
Nov 05, 2020 11:07:50 AM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #2.
Nov 05, 2020 11:07:50 AM org.apache.fop.events.LoggingEventListener processEvent
...
```

#### 3. Second run mn2pdf with internet connection. mn2pdf can't find `times.ttf` and replace it by `SourceSansPro-Regular.ttf` successfully (no downloading, because there are SourceXPro fonts in the folder ~/.metanorma/fonts already) and process PDF successfully:
```
java -Xss5m -Xmx1024m -jar mn2pdf-1.22.jar  --xml-file "test.presentation.xml" --xsl-file "bipm.brochure.presentation.xsl" --pdf-file "test.pdf"
mn2pdf 


Preparing...
Input: Fonts path (~/.metanorma/fonts)
Input: XML (test.presentation.xml)
Input: XSL (bipm.brochure.presentation.xsl)
Output: PDF (test.pdf)

WARNING: Font file '/home/intluser/.metanorma/fonts/arial.ttf' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/arialbd.ttf' (font style 'normal', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/arialbi.ttf' (font style 'italic', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/ariali.ttf' (font style 'italic', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/times.ttf' (font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesbd.ttf' (font style 'normal', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesbi.ttf' (font style 'italic', font weight 'bold') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/timesi.ttf' (font style 'italic', font weight 'normal') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/home/intluser/.metanorma/fonts/WorkSans-Thin.ttf' (font style 'normal', font weight '100') doesn't exist. Replaced by '/home/intluser/.metanorma/fonts/SourceSansPro-Regular.ttf'.
...
Transforming...
Nov 05, 2020 11:29:49 AM org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Nov 05, 2020 11:29:49 AM org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
Nov 05, 2020 11:29:53 AM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #1.
Nov 05, 2020 11:29:53 AM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #2.
```

**Comment by Intelligent2013** [comment]
@opoudjis 
Could you check this command:
```
java -Xss5m -Xmx1024m -jar /Users/nickn/.rvm/gems/ruby-2.6.6/gems/mn2pdf-1.22.1/lib/../bin/mn2pdf.jar -v
```

What is output?

**Comment by ronaldtse** [comment]
Also I'd like to point out that Fontist should be used to install the font.

**Comment by Intelligent2013** [comment]
@ronaldtse just FYI mn2pdf doesn't download SourceXPro and STIX2Math fonts if they are already exist.

**Comment by ronaldtse** [comment]
@opoudjis @Intelligent2013 can we close this now?

**Comment by opoudjis** [comment]
>  java -Xss5m -Xmx1024m -jar /Users/nickn/.rvm/gems/ruby-2.6.6/gems/mn2pdf-1.22.1/lib/../bin/mn2pdf.jar -v
1.22

**Comment by ronaldtse** [comment]
Closing now.
